version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: d3
    versions:
    - 6.6.2
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: grunt-contrib-nodeunit
    versions:
    - 2.1.0
    - 3.0.0
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
    - 3.7.1
  - dependency-name: bower
    versions:
    - 1.8.9
  - dependency-name: grunt-contrib-jshint
    versions:
    - 3.0.0
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: grunt-jsdoc
    versions:
    - 2.4.1
  - dependency-name: tough-cookie
    versions:
    - 2.3.4
  - dependency-name: sshpk
    versions:
    - 1.14.1
  - dependency-name: tar
    versions:
    - 4.4.1
